version: "3"

# looks for other Taskfiles. Optional makes it exe normally if not foun
#includes:
#  docs: ./documentation # will look for ./documentation/Taskfile.yml
#  docker: 
#    taskfile: ./DockerTasks.yml
#    optional: true 

# config ones
# output: outputgroup
# silent: true/false 
# method: checksum|timestamp
# run: always|once|when_changed
# set: [pipefail]
# shopt: [globstar]
vars:
  TFPLAN: .tfplan


#global env
#env: 
#  GREETING: Hey there

# include other .env files
#dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  .build: 
     dir: '{{.USER_WORKING_DIR}}' 
     desc: Builds the task files to task folder
     cmds:

       - |
         cat <<EOF> tasks/terraform-init.sh
         #!/bin/bash

         terraform init
         EOF

       - |
         cat <<EOF> tasks/terraform-init-reconfigure.sh
         #!/bin/bash

         terraform init -reconfigure
         EOF

       - |
         cat <<EOF> tasks/terraform-plan.sh
         #!/bin/bash
         
         terraform plan -out=\${1}
         EOF

       - |
         cat <<EOF> tasks/terraform-apply.sh
         #!/bin/bash
         
         terraform apply \${1}
         EOF

       - |
         cat <<EOF> tasks/default.sh
         #!/bin/bash
         
         echo Type task <command> to run tasks
         echo <command> is one of docs fmt fmtcheck fumpt lint test testdeploy tfclean tools
         EOF

  default:
     dir: '{{.USER_WORKING_DIR}}' 
     desc: Runs the default task
     cmds:
       - sh tasks/default.sh

  init:
    dir: '{{.USER_WORKING_DIR}}'
    desc: Init terraform
    cmds:
       - sh tasks/terraform-init.sh

  init-wrecon:
    dir: '{{.USER_WORKING_DIR}}'
    desc: Init terraform with reconfigure
    cmds:
       - sh tasks/terraform-init-withreconfigure.sh
    # add dependency (run assets before init)
    #deps: [assets]
    #task specific env
    #env: 
    #  GREETING: Hey there

  plan:
    dir: '{{.USER_WORKING_DIR}}'
    desc: Show terraform resources creation
    cmds:
      - sh tasks/terraform-plan.sh "{{.TFPLAN}}"

  apply:
    dir: '{{.USER_WORKING_DIR}}'
    desc: Apply resources creation
    cmds:
     - sh tasks/terraform-apply.sh "{{.TFPLAN}}"